"""API automation scripts (接口自动化模块).

First-version scripts are generated by AI from Feishu API docs; when a run
fails, AI reads the doc again and self-repairs the script (version bump).
"""

from sqlalchemy import ForeignKey, Integer, String, Text, Uuid
from sqlalchemy.orm import Mapped, mapped_column

from src.app.db.database import Base
from src.app.db.models.base import TimestampMixin, UUIDMixin


class ApiScript(Base, UUIDMixin, TimestampMixin):
    """An AI-generated API automation script."""

    __tablename__ = "api_scripts"
    __table_args__ = {"comment": "AI-generated API automation scripts"}

    name: Mapped[str] = mapped_column(String(500), nullable=False)
    project_id: Mapped[str | None] = mapped_column(
        Uuid, ForeignKey("projects.id", ondelete="SET NULL"), nullable=True)
    module: Mapped[str | None] = mapped_column(String(200), nullable=True)
    doc_url: Mapped[str | None] = mapped_column(Text, nullable=True, comment="飞书接口文档 URL")
    language: Mapped[str] = mapped_column(String(20), default="python", nullable=False,
                                          comment="python(pytest) | typescript(playwright)")
    content: Mapped[str] = mapped_column(Text, nullable=False, comment="脚本内容")
    version: Mapped[int] = mapped_column(Integer, default=1, nullable=False)
    status: Mapped[str] = mapped_column(String(20), default="draft", nullable=False,
                                        comment="draft | active | broken | archived")
    endpoints: Mapped[str | None] = mapped_column(Text, nullable=True,
                                                  comment="JSON list of covered endpoints")
    repair_history: Mapped[str | None] = mapped_column(Text, nullable=True,
                                                       comment="JSON list of {version, error, fix_summary, at}")

    def __repr__(self) -> str:
        return f"<ApiScript(name={self.name}, v{self.version}, {self.status})>"


class ApiScriptRun(Base, UUIDMixin, TimestampMixin):
    """One execution of an ApiScript."""

    __tablename__ = "api_script_runs"
    __table_args__ = {"comment": "API script execution records"}

    script_id: Mapped[str] = mapped_column(
        Uuid, ForeignKey("api_scripts.id", ondelete="CASCADE"), nullable=False, index=True)
    status: Mapped[str] = mapped_column(String(20), default="running", nullable=False,
                                        comment="running | passed | failed | error")
    exit_code: Mapped[int | None] = mapped_column(Integer, nullable=True)
    output: Mapped[str | None] = mapped_column(Text, nullable=True, comment="stdout/stderr tail")
    duration_ms: Mapped[int | None] = mapped_column(Integer, nullable=True)
    triggered_by: Mapped[str] = mapped_column(String(20), default="manual", nullable=False,
                                              comment="manual | schedule | self_repair")
    repair_attempt: Mapped[int] = mapped_column(Integer, default=0, nullable=False)

    def __repr__(self) -> str:
        return f"<ApiScriptRun(script={self.script_id}, {self.status})>"
