#!/usr/bin/env node
/**
 * Playwright CLI executor — HTTP front end for the `playwright` CLI.
 *
 * Why this exists: the smart-test backend (python) has no Node runtime, and
 * Playwright's browsers are a heavy, OS-specific install. Rather than fatten
 * the backend image, browser work is delegated to this sidecar, which owns
 * the toolchain and exposes three operations:
 *
 *   GET  /health       → CLI version + which browsers are installed
 *   POST /run          → write spec files, run `playwright test`, return the
 *                        JSON reporter output plus an artifact manifest
 *   POST /screenshot   → run `playwright screenshot <url> <file>` (one-shot
 *                        visual evidence, no spec needed)
 *   POST /cli          → allow-listed `playwright <subcommand>` passthrough (install / pdf / cr)
 *   POST /install-browsers → install browsers into THIS process's filesystem
 *                        (the platform can't: in container mode the runner lives
 *                        in a different container and would install into its own)
 *
 * Each `/run` gets a fresh directory under RUNS_ROOT, so items are isolated
 * exactly like the eval runner isolates harness processes. Artifacts (traces,
 * screenshots, videos) stay on disk and are served back by `/artifact`.
 *
 * Everything here shells out to the real CLI — no `playwright` library
 * imports — so behaviour matches what a developer sees in a terminal.
 *
 * @module playwright-runner/server
 */

import { createServer } from 'node:http'
import { spawn } from 'node:child_process'
import { existsSync } from 'node:fs'
import {
  mkdir, readFile, readdir, stat, symlink, writeFile,
} from 'node:fs/promises'
import { appendFileSync } from 'node:fs'
import { dirname, extname, join, normalize, relative, resolve, sep } from 'node:path'
import { randomUUID } from 'node:crypto'

const PORT = Number(process.env.PORT ?? 5015)
const HOST = process.env.HOST ?? '0.0.0.0'
/** Directory holding the installed `@playwright/test` + browsers. */
const PW_HOME = process.env.PW_HOME ?? '/opt/pw'

/**
 * `playwright` CLI 的可执行路径。
 *
 * Windows 上 npm 在 `node_modules/.bin/` 生成三个文件：`playwright`（sh 脚本）、
 * `playwright.cmd`、`playwright.ps1`。而 `spawn` 不走 shell，CreateProcess 只认
 * `.exe/.cmd/.bat` —— 指向那个无扩展名的 sh 脚本必然失败（经典的 "spawn npm
 * ENOENT" 同款）。症状具有误导性：`/health` 报 `available:false`，看起来像
 * "浏览器没装"，实际是 CLI 根本没起来；`install-browsers` 也会一并失败。
 */
function resolvePwCli() {
  if (process.env.PW_CLI) return process.env.PW_CLI
  const bin = join(PW_HOME, 'node_modules', '.bin')
  const candidates = process.platform === 'win32'
    ? ['playwright.cmd', 'playwright.exe', 'playwright']
    : ['playwright']
  for (const name of candidates) {
    const candidate = join(bin, name)
    if (existsSync(candidate)) return candidate
  }
  // 一个都不在时回候选里的第一个：让后续报错带上"期望在哪儿"，而不是一句 ENOENT
  return join(bin, candidates[0])
}

const PW_CLI = resolvePwCli()
const RUNS_ROOT = process.env.RUNS_ROOT ?? '/work/runs'
const DEFAULT_TIMEOUT_MS = Number(process.env.RUN_TIMEOUT_MS ?? 300_000)
/** Serve artifact bytes up to this size; larger files are listed but not inlined. */
const INLINE_ARTIFACT_LIMIT = Number(process.env.INLINE_ARTIFACT_LIMIT ?? 2_000_000)
/** 装浏览器是几十到上百 MB 的下载 + 解包，给足时间（默认 15 分钟）。 */
const INSTALL_TIMEOUT_MS = Number(process.env.INSTALL_TIMEOUT_MS ?? 900_000)

// ── small helpers ─────────────────────────────────────────────────────────

/** Run a command, capturing stdout/stderr; never rejects on a non-zero exit.
 *
 * ``logFile`` 会把 stdout/stderr 边跑边追加到文件里——进度面板靠它显示
 * 「CLI 此刻在做什么」。只靠最终报告的话，一次几十秒的执行在前端就是一片空白。
 */
function run(cmd, args, { cwd, env, timeoutMs, logFile }) {
  return new Promise((resolvePromise) => {
    const started = Date.now()
    const child = spawn(cmd, args, { cwd, env: { ...process.env, ...env } })
    let stdout = ''
    let stderr = ''
    let timedOut = false
    const timer = setTimeout(() => {
      timedOut = true
      child.kill('SIGKILL')
    }, timeoutMs)
    const writeLog = (chunk) => {
      if (logFile === undefined) return
      try {
        appendFileSync(logFile, chunk)
      } catch {
        // 日志写不进去不能影响执行本身
      }
    }
    child.stdout.on('data', (chunk) => { stdout += chunk; writeLog(chunk) })
    child.stderr.on('data', (chunk) => { stderr += chunk; writeLog(chunk) })
    child.on('error', (error) => {
      clearTimeout(timer)
      resolvePromise({ code: -2, stdout, stderr: `${stderr}${error.message}`, durationMs: Date.now() - started, timedOut })
    })
    child.on('close', (code) => {
      clearTimeout(timer)
      resolvePromise({ code: code ?? -1, stdout, stderr, durationMs: Date.now() - started, timedOut })
    })
  })
}

/**
 * 逐步进度 reporter 的源码，写进每个 run 目录。
 *
 * 为什么用自定义 reporter 而不是解析日志：`list` reporter 的输出是给人看的、
 * 格式随时会变；reporter API 的 `onTestEnd` 给的是结构化数据（用例名/状态/耗时），
 * 前端能直接算「跑到第几条、过了几条」。每行一个 JSON，边跑边落盘，
 * 后端读文件即可，不需要长连接。
 */
const PROGRESS_REPORTER = `// generated by playwright-runner — do not edit
import { appendFileSync } from 'node:fs'

export default class ProgressReporter {
  constructor(options = {}) {
    this.path = options.path ?? 'progress.ndjson'
  }

  write(payload) {
    try {
      appendFileSync(this.path, JSON.stringify({ ...payload, at: Date.now() }) + '\\n')
    } catch {
      // 进度写不进去不该让用例失败
    }
  }

  onBegin(config, suite) {
    this.write({ event: 'begin', total: suite.allTests().length, workers: config.workers })
  }

  onTestEnd(test, result) {
    this.write({
      event: 'test',
      title: test.title,
      fullTitle: test.titlePath().filter(Boolean).join(' › '),
      status: result.status,
      duration: result.duration,
      retry: result.retry,
    })
  }

  onEnd(result) {
    this.write({ event: 'end', status: result.status })
  }
}
`

/** Reject paths that would escape the run directory. */
function safeJoin(root, candidate) {
  const target = resolve(root, candidate)
  if (target !== root && !target.startsWith(root + sep)) {
    throw new Error(`path escapes run directory: ${candidate}`)
  }
  return target
}

/** Recursively list files under a directory, relative to it. */
async function walkFiles(root, current = root) {
  const out = []
  let entries
  try {
    entries = await readdir(current, { withFileTypes: true })
  } catch {
    return out
  }
  for (const entry of entries) {
    const full = join(current, entry.name)
    if (entry.isDirectory()) out.push(...await walkFiles(root, full))
    else if (entry.isFile()) {
      const info = await stat(full)
      out.push({ path: relative(root, full), size: info.size })
    }
  }
  return out
}

async function readJsonBody(request) {
  const chunks = []
  for await (const chunk of request) chunks.push(chunk)
  const raw = Buffer.concat(chunks).toString('utf8')
  if (raw.trim() === '') return {}
  return JSON.parse(raw)
}

function sendJson(response, status, payload) {
  const body = JSON.stringify(payload)
  response.writeHead(status, {
    'content-type': 'application/json; charset=utf-8',
    'content-length': Buffer.byteLength(body),
  })
  response.end(body)
}

// ── playwright config generation ──────────────────────────────────────────

/** Keys the caller may set on Playwright's `use` block. */
const USE_KEYS = [
  'baseURL', 'viewport', 'deviceScaleFactor', 'isMobile', 'hasTouch',
  'userAgent', 'locale', 'timezoneId', 'extraHTTPHeaders',
  'ignoreHTTPSErrors', 'colorScheme', 'geolocation', 'permissions',
  'httpCredentials', 'storageState', 'javaScriptEnabled',
]

/**
 * Build a self-contained `playwright.config.mjs`. Callers describe intent
 * declaratively (`baseURL`, `device`, `viewport`, …) instead of shipping a
 * config file, so the runner owns reporter/outputDir wiring and every run is
 * reported identically.
 */
function buildConfig({
  options = {}, outDir, htmlReportDir, jsonReportPath, progressPath, timeout, retries, workers,
}) {
  const use = {}
  for (const key of USE_KEYS) {
    if (options[key] !== undefined) use[key] = options[key]
  }
  // A device descriptor is a `use` preset; spread it first so an explicit
  // option (e.g. locale) still wins over the device default.
  const device = options.device
  const deviceSpread = device === undefined ? '{}' : `devices[${JSON.stringify(device)}]`

  // Multi-browser runs become `projects`, so one report covers the whole
  // matrix. WebKit gets isMobile/hasTouch stripped: Playwright cannot emulate
  // a mobile WebKit off macOS (its own CLI deletes the same two keys for the
  // same reason), and keeping them makes the project fail on Linux.
  const browsers = Array.isArray(options.browsers) && options.browsers.length > 0
    ? options.browsers.map(String)
    : null
  const projectsBlock = browsers === null ? '' : `
  projects: [
${browsers.map((name) => {
    const extra = name === 'webkit' ? ', isMobile: undefined, hasTouch: undefined' : ''
    return `    { name: ${JSON.stringify(name)}, use: { browserName: ${JSON.stringify(name)}${extra} } },`
  }).join('\n')}
  ],`

  // The html report is what makes failures debuggable: it bundles screenshots,
  // the error context and trace.zip into one self-contained folder whose links
  // are all relative — so serving the folder statically gives the full official
  // report UI (including trace playback) with no extra moving parts.
  const htmlReporter = options.htmlReport === false
    ? ''
    : `['html', { outputFolder: ${JSON.stringify(htmlReportDir)}, open: 'never' }], `

  return `// generated by playwright-runner — do not edit
import { defineConfig, devices } from '@playwright/test'

const baseUse = ${JSON.stringify(use, null, 2)}

export default defineConfig({
  testDir: ${JSON.stringify(options.testDir ?? '.')},
  testMatch: ${JSON.stringify(options.testMatch ?? ['**/*.spec.@(js|mjs|ts)', '**/*.test.@(js|mjs|ts)'])},
  fullyParallel: ${options.fullyParallel === true},
  // A stray "test.only" left behind while debugging would otherwise run a
  // single case and let the whole file report success.
  forbidOnly: true,
  retries: ${Number(retries ?? 0)},
  workers: ${Number(workers ?? 1)},
  timeout: ${Number(timeout ?? 60_000)},
  outputDir: ${JSON.stringify(outDir)},
  reporter: [${htmlReporter}['json', { outputFile: ${JSON.stringify(jsonReportPath)} }], ['list'],
    ['./progress-reporter.mjs', { path: ${JSON.stringify(progressPath ?? 'progress.ndjson')} }]],
  use: {
    // Device descriptors carry defaultBrowserType, and for an iPhone that is
    // webkit — pin chromium after the spread so one browser install covers
    // every device (the UA/viewport/touch emulation is what the site sees).
    ...${deviceSpread},
    ...baseUse,
    browserName: 'chromium',
    trace: ${JSON.stringify(options.trace ?? 'retain-on-failure')},
    screenshot: ${JSON.stringify(options.screenshot ?? 'only-on-failure')},
    // Failure video is the cheapest evidence a reviewer can consume; only
    // failures keep it, so the disk cost stays bounded.
    video: ${JSON.stringify(options.video ?? 'retain-on-failure')},
  },${projectsBlock}
})
`
}

// ── operations ────────────────────────────────────────────────────────────

async function opHealth() {
  const version = await run(PW_CLI, ['--version'], { cwd: PW_HOME, timeoutMs: 30_000 })
  return {
    available: version.code === 0,
    version: (version.stdout + version.stderr).trim(),
    cli: PW_CLI,
    browsers: await listBrowsers(),
    runsRoot: RUNS_ROOT,
    node: process.version,
  }
}

/**
 * Where the browsers actually live. `PLAYWRIGHT_BROWSERS_PATH` wins; without
 * it Playwright uses a per-platform cache dir, and reporting "(none)" because
 * we looked in the wrong place would be actively misleading.
 */
function browsersRoot() {
  if (process.env.PLAYWRIGHT_BROWSERS_PATH) return process.env.PLAYWRIGHT_BROWSERS_PATH
  const home = process.env.HOME ?? process.env.USERPROFILE ?? ''
  if (process.platform === 'darwin') return join(home, 'Library', 'Caches', 'ms-playwright')
  if (process.platform === 'win32') return join(home, 'AppData', 'Local', 'ms-playwright')
  return join(home, '.cache', 'ms-playwright')
}

async function listBrowsers() {
  try {
    return (await readdir(browsersRoot())).filter((name) => !name.startsWith('.'))
  } catch {
    return []
  }
}

/** `POST /run` — write specs and drive `playwright test`. */
async function opRun(body) {
  const files = body.files
  if (files === undefined || typeof files !== 'object' || Object.keys(files).length === 0) {
    return { status: 400, payload: { ok: false, error: 'files is required: { "path.spec.ts": "<source>" }' } }
  }
  const timeoutMs = Number(body.timeoutMs ?? DEFAULT_TIMEOUT_MS)
  // 调用方可以指定 runId：后端要先把执行记录落库（status=running），才能让
  // 前端在跑的当下就找到进度文件；由 runner 自己生成的话后端拿不到这个映射。
  const runId = typeof body.runId === 'string' && /^[A-Za-z0-9._-]{1,120}$/.test(body.runId)
    ? body.runId
    : `${new Date().toISOString().replace(/[:.]/g, '-')}-${randomUUID().slice(0, 8)}`
  const runDir = join(RUNS_ROOT, runId)
  const outDir = join(runDir, 'test-results')
  const artifactsDir = join(runDir, 'artifacts')
  await mkdir(runDir, { recursive: true })
  await mkdir(artifactsDir, { recursive: true })

  // Specs import '@playwright/test'; ESM ignores NODE_PATH, so make the
  // runner's install visible through a node_modules symlink in the run dir.
  await symlink(join(PW_HOME, 'node_modules'), join(runDir, 'node_modules'), 'dir')

  for (const [file, source] of Object.entries(files)) {
    const target = safeJoin(runDir, file)
    await mkdir(dirname(target), { recursive: true })
    await writeFile(target, String(source), 'utf8')
  }

  const reportPath = join(runDir, 'report.json')
  const htmlReportDir = join(runDir, 'html-report')
  const configPath = join(runDir, 'playwright.config.mjs')
  const progressPath = join(runDir, 'progress.ndjson')
  await writeFile(join(runDir, 'progress-reporter.mjs'), PROGRESS_REPORTER, 'utf8')
  await writeFile(configPath, buildConfig({
    options: body.options ?? {},
    outDir,
    htmlReportDir,
    jsonReportPath: reportPath,
    progressPath: 'progress.ndjson',
    timeout: body.testTimeoutMs,
    retries: body.retries,
    workers: body.workers,
  }), 'utf8')

  const specs = [];
  if (typeof body.spec === 'string') specs.push(body.spec)
  else if (Array.isArray(body.spec)) specs.push(...body.spec)

  const args = ['test', '--config', configPath]
  if (specs.length > 0) args.push(...specs)
  if (typeof body.grep === 'string' && body.grep !== '') args.push('--grep', body.grep)

  const result = await run(PW_CLI, args, {
    cwd: runDir,
    timeoutMs,
    logFile: join(runDir, 'stdout.log'),
    env: {
      PLAYWRIGHT_BROWSERS_PATH: browsersRoot(),
      PW_RUN_ID: runId,
      // CI-style defaults; the generated config carries the real settings.
      CI: process.env.CI ?? '1',
    },
  })

  let report = null
  if (existsSync(reportPath)) {
    try {
      report = JSON.parse(await readFile(reportPath, 'utf8'))
    } catch (error) {
      report = { parseError: String(error) }
    }
  }

  const artifacts = []
  for (const root of [artifactsDir, outDir]) {
    for (const file of await walkFiles(root)) {
      artifacts.push({
        name: relative(runDir, join(root, file.path)),
        path: relative(runDir, join(root, file.path)),
        size: file.size,
      })
    }
  }

  return {
    status: 200,
    payload: {
      ok: result.code === 0 && !result.timedOut,
      runId,
      exitCode: result.code,
      timedOut: result.timedOut,
      durationMs: result.durationMs,
      stats: report?.stats ?? null,
      tests: summarizeTests(report, runDir),
      errors: (report?.errors ?? []).map((e) => e.message ?? String(e)).slice(0, 10),
      artifacts,
      htmlReport: existsSync(htmlReportDir) ? 'html-report' : null,
      stdout: tail(result.stdout, 20_000),
      stderr: tail(result.stderr, 8_000),
    },
  }
}

/**
 * Playwright states a test's outcome against the *expectation*
 * (`expected` / `unexpected`), so every downstream reader would otherwise have
 * to translate it — and a `!== 'passed'` check silently reports every passing
 * case as failed. Normalize once here.
 */
function normalizeStatus(status) {
  return {
    expected: 'passed',
    unexpected: 'failed',
    timedOut: 'timedOut',
    interrupted: 'interrupted',
  }[status] ?? status
}

/** Absolute in-container path → path relative to the run dir (when inside). */
function relToRun(runDir, filePath) {
  if (typeof filePath !== 'string' || filePath === '') return undefined
  const rel = relative(runDir, filePath)
  return rel.startsWith('..') ? undefined : rel
}

/** The reporter hands stdout/stderr back as `[{ text }]` chunks. */
function joinChunks(chunks) {
  if (!Array.isArray(chunks)) return undefined
  const text = chunks.map((chunk) => (typeof chunk === 'string' ? chunk : chunk?.text ?? '')).join('')
  return text === '' ? undefined : text
}

/** Flatten the JSON reporter's nested suites into one row per test. */
function summarizeTests(report, runDir) {
  if (report === null || report === undefined) return []
  const rows = []
  const visit = (suite, trail) => {
    for (const child of suite.suites ?? []) visit(child, [...trail, child.title].filter(Boolean))
    for (const spec of suite.specs ?? []) {
      for (const test of spec.tests ?? []) {
        const result = (test.results ?? [])[test.results.length - 1] ?? {}
        const errorLocation = result.errorLocation
        rows.push({
          // Kept so a "rerun only the failures" flow can feed these back to
          // the CLI through --test-list.
          id: spec.id,
          title: spec.title,
          fullTitle: [...trail, spec.title].filter(Boolean).join(' › '),
          file: relToRun(runDir, spec.file),
          line: spec.line,
          tags: spec.tags ?? [],
          projectName: test.projectName,
          status: normalizeStatus(test.status ?? result.status ?? 'unknown'),
          rawStatus: test.status ?? result.status,
          duration: result.duration ?? 0,
          retry: result.retry ?? 0,
          error: result.error?.message ? String(result.error.message).slice(0, 4_000) : undefined,
          // Which line of the author's own spec failed — saves the reader from
          // parsing a stack trace to find it.
          errorLocation: errorLocation === undefined ? undefined : {
            file: relToRun(runDir, errorLocation.file) ?? errorLocation.file,
            line: errorLocation.line,
            column: errorLocation.column,
          },
          // console.log from the spec (the documented recon workflow) — was
          // dropped before, which silently broke "print the DOM and look".
          stdout: joinChunks(result.stdout),
          stderr: joinChunks(result.stderr),
          annotations: (result.annotations ?? []).map((a) => ({ type: a.type, description: a.description })),
          attachments: (result.attachments ?? []).map((a) => ({
            name: a.name,
            contentType: a.contentType,
            path: relToRun(runDir, a.path),
          })),
        })
      }
    }
  }
  for (const suite of report.suites ?? []) visit(suite, [])
  return rows
}

/** `POST /screenshot` — one-shot `playwright screenshot` CLI call. */
async function opScreenshot(body) {
  const url = body.url
  if (typeof url !== 'string' || url === '') {
    return { status: 400, payload: { ok: false, error: 'url is required' } }
  }
  const runId = `${new Date().toISOString().replace(/[:.]/g, '-')}-shot-${randomUUID().slice(0, 8)}`
  const runDir = join(RUNS_ROOT, runId)
  const artifactsDir = join(runDir, 'artifacts')
  await mkdir(artifactsDir, { recursive: true })
  const target = join(artifactsDir, body.filename ?? 'screenshot.png')

  const args = ['screenshot', '--browser', String(body.browser ?? 'chromium')]
  if (body.device !== undefined) args.push('--device', String(body.device))
  if (body.fullPage === true) args.push('--full-page')
  if (body.waitForSelector !== undefined) args.push('--wait-for-selector', String(body.waitForSelector))
  if (body.viewport !== undefined) args.push('--viewport-size', String(body.viewport))
  if (body.waitForTimeout !== undefined) args.push('--wait-for-timeout', String(body.waitForTimeout))
  args.push(url, target)

  const result = await run(PW_CLI, args, {
    cwd: runDir,
    timeoutMs: Number(body.timeoutMs ?? 120_000),
    env: { PLAYWRIGHT_BROWSERS_PATH: browsersRoot() },
  })

  const payload = {
    ok: result.code === 0 && existsSync(target),
    runId,
    exitCode: result.code,
    durationMs: result.durationMs,
    path: relative(RUNS_ROOT, target),
    stdout: tail(result.stdout, 4_000),
    stderr: tail(result.stderr, 4_000),
  }
  if (payload.ok) payload.dataUri = await asDataUri(target)
  return { status: 200, payload }
}

/** `POST /cli` — allow-listed `playwright <subcommand>` passthrough. */
// 只留**没有专用工具**的子命令。`--version` / `screenshot` / `test` 曾也在表里，
// 但平台分别有 webui_runner_status / webui_screenshot / webui_run_spec——那几个
// 返回结构化结果（report / artifacts / dataUri），比读 CLI stdout 可靠。留着它们
// 等于给 agent 留了一条绕开结构化工具、拿到难解析输出的路。
const CLI_ALLOWLIST = new Set(['install', 'pdf', 'cr'])

async function opCli(body) {
  const args = body.args
  if (!Array.isArray(args) || args.length === 0) {
    return { status: 400, payload: { ok: false, error: 'args is required: ["--version"]' } }
  }
  if (!CLI_ALLOWLIST.has(String(args[0]))) {
    return {
      status: 400,
      payload: { ok: false, error: `subcommand not allowed: ${args[0]}`, allowed: [...CLI_ALLOWLIST] },
    }
  }
  const result = await run(PW_CLI, args.map(String), {
    cwd: RUNS_ROOT,
    timeoutMs: Number(body.timeoutMs ?? 120_000),
    env: { PLAYWRIGHT_BROWSERS_PATH: browsersRoot() },
  })
  return {
    status: 200,
    payload: {
      ok: result.code === 0,
      exitCode: result.code,
      durationMs: result.durationMs,
      stdout: tail(result.stdout, 20_000),
      stderr: tail(result.stderr, 8_000),
    },
  }
}

async function asDataUri(path) {
  const info = await stat(path)
  if (info.size > INLINE_ARTIFACT_LIMIT) return undefined
  const ext = extname(path).toLowerCase()
  const mime = ext === '.png' ? 'image/png'
    : ext === '.jpg' || ext === '.jpeg' ? 'image/jpeg'
      : ext === '.zip' ? 'application/zip'
        : ext === '.webm' ? 'video/webm'
          : 'application/octet-stream'
  return `data:${mime};base64,${(await readFile(path)).toString('base64')}`
}

function tail(text, limit) {
  if (text === undefined || text === null) return ''
  return text.length <= limit ? text : `…\n${text.slice(-limit)}`
}

/**
 * `POST /install-browsers` — 在 **runner 自己的文件系统**里装浏览器。
 *
 * 为什么由 runner 装、而不是平台跑一条命令：容器形态下 runner 在独立容器里，
 * 平台去执行 `playwright install` 会装进平台自己的文件系统（runner 根本看不到），
 * 而 `/health` 报的是 runner 这边的 `browsersRoot()`。让 runner 装自己，
 * 原生与容器两种形态共用同一套代码。
 *
 * 系统依赖（Linux 上那批 apt 包）需要 root：容器里本来就是 root，直接带
 * `--with-deps`；宿主机上的普通用户装不了，就不带，改由调用方把「需要 root 的
 * 那条命令」交给用户复制 —— 比让用户去猜 `--with-deps` 是什么强。
 */
async function opInstallBrowsers(body = {}) {
  const wanted = Array.isArray(body.browsers) && body.browsers.length > 0
    ? body.browsers.filter((name) => typeof name === 'string' && name.length > 0)
    : ['chromium']
  const isRoot = typeof process.getuid === 'function' && process.getuid() === 0
  const withDeps = typeof body.withDeps === 'boolean' ? body.withDeps : isRoot
  const args = ['install']
  if (withDeps) args.push('--with-deps')
  args.push(...wanted)

  await mkdir(RUNS_ROOT, { recursive: true })
  const logFile = join(RUNS_ROOT, 'install-browsers.log')
  const result = await run(PW_CLI, args, {
    cwd: PW_HOME, timeoutMs: INSTALL_TIMEOUT_MS, logFile,
  })
  const command = `${PW_CLI} ${args.join(' ')}`
  const browsers = await listBrowsers()
  const root = browsersRoot()

  if (result.code !== 0) {
    const detail = tail((result.stderr || result.stdout || '').trim(), 2000)
    return {
      ok: false,
      command,
      browsersRoot: root,
      browsers,
      durationMs: result.durationMs,
      error: detail || `退出码 ${result.code}${result.timedOut ? '（超时）' : ''}`,
      hint: withDeps
        ? '若为网络问题，设 PLAYWRIGHT_DOWNLOAD_HOST 指向镜像后重试（国内可用 https://cdn.npmmirror.com/binaries/playwright）'
        : `系统依赖需要 root，在宿主机上执行：sudo ${PW_CLI} install --with-deps ${wanted.join(' ')}`,
    }
  }
  return {
    ok: true, command, browsersRoot: root, browsers,
    durationMs: result.durationMs, log: logFile,
  }
}

// ── routing ───────────────────────────────────────────────────────────────

const ROUTES = {
  'GET /health': async () => ({ status: 200, payload: await opHealth() }),
  'POST /run': opRun,
  'POST /screenshot': opScreenshot,
  'POST /cli': opCli,
  'POST /install-browsers': opInstallBrowsers,
}

const server = createServer(async (request, response) => {
  const url = new URL(request.url, `http://${request.headers.host ?? 'localhost'}`)
  const key = `${request.method} ${url.pathname}`

  try {
    // Artifact download lives outside the table: it streams a file.
    if (request.method === 'GET' && url.pathname === '/artifact') {
      const runId = url.searchParams.get('run') ?? ''
      const rel = url.searchParams.get('path') ?? ''
      const runDir = safeJoin(RUNS_ROOT, runId)
      const target = safeJoin(runDir, rel)
      if (!existsSync(target)) return sendJson(response, 404, { ok: false, error: 'artifact not found' })
      const info = await stat(target)
      response.writeHead(200, {
        'content-type': extname(target) === '.png' ? 'image/png' : 'application/octet-stream',
        'content-length': info.size,
      })
      response.end(await readFile(target))
      return
    }

    const handler = ROUTES[key]
    if (handler === undefined) {
      return sendJson(response, 404, { ok: false, error: `no route for ${key}`, routes: Object.keys(ROUTES) })
    }
    const body = request.method === 'POST' ? await readJsonBody(request) : {}
    const result = await handler(body)
    // Handlers either return `{status, payload}` or a bare payload (200).
    const { status, payload } = (result !== null && typeof result === 'object'
      && 'payload' in result) ? result : { status: 200, payload: result }
    sendJson(response, status, payload)
  } catch (error) {
    sendJson(response, 500, { ok: false, error: String(error?.stack ?? error) })
  }
})

async function main() {
  await mkdir(RUNS_ROOT, { recursive: true })
  const health = await opHealth()
  console.log(`[playwright-runner] ${health.version || 'CLI not found'} listening on ${HOST}:${PORT}`)
  console.log(`[playwright-runner] cli=${PW_CLI} runs=${RUNS_ROOT} browsers=${health.browsers.join(', ') || '(none)'}`)
  if (!health.available) {
    console.warn('[playwright-runner] WARNING: `playwright --version` failed — run `playwright install chromium`')
  }
  server.listen(PORT, HOST)
}

main()
